
local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)

cfg.groups = {
  ["superadmindono"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um SuperAdmin."}) end},
    "player.group.add",
    "player.group.remove",
    "player.givemoney",
    "player.giveitem",
	"admin.godmode",
	"process.metanfetaminacasa"
  },
  ["admindono"] = {
    "admin.tickets",
    "admin.announce",
    "player.list",
	"admin.godmode",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.unban",
    "player.noclip",
    "player.custom_emote",
	"armas.traficante",
    "player.custom_sound",
    "player.display_custom",
	"police.menu_interaction",
    "player.coords",
    "player.tptome",
	"radar.pass",
	"admin.deleteveh",
	"admin.spawnveh",
	"admin.godmode",
	"player.tptowaypoint",
	"player.cmd_mask",
	"admin.easy_unjail",
	"police.door",
	"police.license",
	"police.licensearm",
	"admin.spikes",
    "player.tpto"
  },
  ["moderadono"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~r~moderador."}) end},
    "admin.tickets",
    "admin.announce",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
	"player.ban",
    "player.display_custom",
	"police.menu_interaction",
    "player.tptome",
	"radar.pass",
	"admin.deleteveh",
	"player.tptowaypoint",
	"player.cmd_mask",
	"admin.easy_unjail",
	"police.door",
	"police.license",
	"police.licensearm",
	"admin.spikes",
    "player.tpto"
  },   
  ["staff"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~r~staff."}) end},
    "admin.tickets",
    "admin.announce",
    "player.whitelist",
    "player.unwhitelist",
  },
  -- the group user is auto added to all logged players
  ["user"] = {
  "coma.caller",
  "coma.skipper",
    "police.menu",
	"venda.todos",
    "player.phone",
	"player.loot",
	"player.store_armor",
	"player.fix_haircut",
	"player.emotes",
    "player.player_menu",
    "player.store_money",
    "player.store_weapons",
    "player.check",
    "police.check",
    "player.calladmin",
	"spawn.garagem",
	"emergency_heal",
	"player.skip_coma",
    "police.seizable" -- can be seized
  }, 
  
  ["donategold"] = {
    "donategold.paycheck",
	"donater.vehicle"
  }, 
  ["donateprata"] = {
    "donateprata.paycheck",
	"donater.vehicle"
  }, 
  ["donateammu"] = {
    "donater.loadshop"
  }, 
  
    ["[PMERJ] Comandante Geral"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"pmerj.cloakroom",
	"rota.paycheck",
	"rota.weapons",
	"comandante.paycheck",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ---PM 
  ["[PMERJ] Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"sargentopmesp.weapons",
	"police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"pmerj.cloakroom",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
	"coronel.paycheck",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,   
  ["[PMERJ] Ten.Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"pmerj.cloakroom",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"tencoronel.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,   
  ["[PMERJ] Major"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"pmerj.cloakroom",
	"police.askid",
	"major.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Capitão"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"pmerj.cloakroom",
	"capitao.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"cabopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
	"pmerj.cloakroom",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"tenente.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Sub.Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"cabopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
	"pmerj.cloakroom",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"subtenente.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "cmdgeral.cloakroom",
	"cabopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
	"pmerj.cloakroom",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"sargento.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Soldado"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "pmerj.cloakroom",
	"cabopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
	"soldadopmesp.cloakroom",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"soldado.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] 2º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "pmerj.cloakroom",
	"cabopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"pmerj.cloakroom",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"sargento.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] 3º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "pmerj.cloakroom",
	"cabopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
	"pmerj.cloakroom",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"sargento.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Cabo"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "pmerj.cloakroom",
	"soldadopmesp.weapons",
    "police.pc",
	"radar.pass",
	"pmerj.cloakroom",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"cabo.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[PMERJ] Recruta"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "pmerj.cloakroom",
	"soldadopmesp.weapons",
	"rota.cloakroom",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  -- BOPE
  ["[BOPE] Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"bope.cloakroom",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,   
  ["[BOPE] Tenete Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"bope.cloakroom",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,   
  ["[BOPE] Major"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"bope.cloakroom",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] Capitão"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"bope.cloakroom",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] 1º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
	"bope.cloakroom",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] 2º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"bope.cloakroom",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] Sub-Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"bope.cloakroom",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
	
	}, 
  ["[BOPE] Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
	"bope.cloakroom", 
    "police.fine",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } , 
  ["[BOPE] 1º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"bope.cloakroom", 
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] 2º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"bope.cloakroom", 
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] 3º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
	"bope.cloakroom", 
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] Cabo"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"bope.cloakroom", 
    "police.announce",
	"police.askid",
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,  
  ["[BOPE] Soldado"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"bope.cloakroom", 
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,
    ["[BOPE] Recruta"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "rota.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"bope.cloakroom", 
	"rota.paycheck",
	"rota.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  } ,
   ["Policia Federal"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
      onleave = function(player) vRPclient.setCop(player,{false}) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "federal.cloakroom",
	"sargentopmesp.weapons",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"federal.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"policiafederal.paycheck",
	"policiafederal.weapons",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  },
  ["[PMERJ] Aguia"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
      onleave = function(player) vRPclient.setCop(player,{false}) end
    },
    "player.list",
	"aguiapmsp.loadshop",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
	"colete.weapons",
    "aguia.cloakroom",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"aguia.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"aguiapmesp.paycheck",
	"aguiapmesp.weapons",
	"police.weapon_search",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  },
  ["Agente PF"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
      onleave = function(player) vRPclient.setCop(player,{false}) end
    },
    "player.list",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"pf.loadshop",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
	"police.door",
    "police.menu",
    "federal.cloakroom",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
	"colete.weapons",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "sargentopmesp.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"agtpf.paycheck",
	"pf.loadshop",
	"police.weapons",
	"police.weapon_search",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  },
  ["Delegado PF"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
      onleave = function(player) vRPclient.setCop(player,{false}) end
    },
    "player.group.add",
    "player.group.remove",
    "player.list",
	"delpf.loadshop",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"colete.weapons",
	"police.door",
	"captain.door",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "federal.cloakroom",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "sargentopmesp.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"delpf.paycheck",
	"police.weapons",
	"delpf.loadshop",
	"police.weapon_search",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  },
  ["Delegada PF"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
      onleave = function(player) vRPclient.setCop(player,{false}) end
    },
    "player.group.add",
    "player.group.remove",
    "player.list",
	"delpf.loadshop",
	"captain.door",
	"police.door",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"colete.weapons",
	"police.easy_cuff",
	"police.drag",
	"police.menu_interaction",
	"police.door",
    "police.menu",
    "federal.cloakroom",
    "police.pc",
	"radar.pass",
	"holdup.police",
	"pm1.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
	"police.license",
	"police.licensearm",
	"bank.police",
    "sargentopmesp.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
	"police.askid",
	"delpf.paycheck",
	"police.weapons",
	"delpf.loadshop",
	"police.weapon_search",
    "-police.store_weapons",
    "-police.seizable" -- negative permission, police can't seize itself, even if another group add the permission
  },
  ["Chefe SAMU"] = {
    _config = { gtype = "job" },
	"player.group.add",
    "player.group.remove",
    "emergency.revive",
    "emergency.shop",
	"emergency_heal",
    "emergency.service",
	"hospital.garagem",
	"emergency.paycheck",
	"emergency.medkit",
	"paramedicosamu.paycheck",
	"emscheck.revive",
	"radar.pass",
	"samu.cloakroom"
  },
   ["Estagiario SAMU"] = {
    _config = { gtype = "job" },
	"player.group.add",
    "player.group.remove",
    "emergency.revive",
    "emergency.shop",
	"emergency_heal",
    "emergency.service",
	"hospital.garagem",
	"emergency.medkit",
	"estagiariosamu.paycheck",
	"emscheck.revive",
	"radar.pass",
	"emergency.paycheck",
	"samu.cloakroom"
  },
    ["Medico SAMU"] = {
    _config = { gtype = "job" },
	"player.group.add",
    "player.group.remove",
    "emergency.revive",
    "emergency.shop",
	"emergency_heal",
    "emergency.service",
	"aguiasamu.garagem",
	"hospital.garagem",
	"emergency.medkit",
	"medicosamu.paycheck",
	"emergency.paycheck",
	"emscheck.revive",
	"radar.pass",
	"samu.cloakroom"
  },
  ["Chaveiro"] = {
    _config = { gtype = "job"},
	"carjacker.lockpick",
      "vehicle.repair",
    "vehicle.replace",
		"repair.paycheck"
	  },
  ["Mecânico"] = {
    _config = { gtype = "job"},
    "vehicle.repair",
    "vehicle.replace",
	"repair.paycheck",
	"mission.repair.satellite_dishes",
	"mission.repair.wind_turbines",
    "repair.service",
	"repair.garagem"
  },
  ["Taxi"] = {
    _config = { gtype = "job" },
    "taxi.service",
	"taxi.paycheck",
	"mission.taxi.passenger",
	"taxi.garagem"
  },
  ["Jornalista"] = {
    _config = { gtype = "job" },
	"jornalista.paycheck",
	"traje.jornalista"
  },
  ["Entregador"] = {
    _config = { gtype = "job" },
	"delivery.paycheck",
	"delivery.service",
    "mission.delivery.food",
	"delivery.garagem"
  },
  ["Ladrão de Carros"] = {
    _config = { gtype = "job" },
    "mission.carjack.vehicle",
	"carjacker.lockpick"
  },
  ["Traficante de Maconha"] = {
    _config = { gtype = "job" },
	"harvest.weed",
	"sell.weed",
	"process.weed"
  },
    ["Prostituta"] = {
    _config = { gtype = "job" },
    "mission.prostituta",
    "prostituta.paycheck",
    "puta.service"
  },
  ["Traficante de Metanfetamina"] = {
    _config = { gtype = "job" },
	"harvest.metanfetamina",
	"sell.metanfetamina",
	"process.metanfetamina"
  },  
  ["Traficante de Cocaina"] = {
    _config = { gtype = "job" },
	"harvest.cocaina",
	"process.cocaina",
	"sell.cocaina"
  },  
  ["Traficante de Tartaruga"] = {
    _config = { gtype = "job" },
    "harvest.tartaruga",
	"process.Tartaruga",
	"mergulhador.cloakroom"
  },
  
  ["Lider A.L"] = {
    _config = { gtype = "job" },
	"favela.dom",
	"harvest.weed",
	"process.weed",
	"sell.weed"

  },
   ["Chefe Comando Vermelho"] = {
    _config = { gtype = "job" },
	"harvest.metanfetamina",
	"process.metanfetamina",
	"mission.delivery.metanfetamina",
	"sell.metanfetamina",
	"mission.delivery.pot3",
	"police.seize.weapons",
	"police.handcuff",
	"favela.dom"
  },
     ["Chefe Corleone"] = {
    _config = { gtype = "job" },
	"corleone.gunshops",
	"harvest.weed",
	"harvest.cocaina",
    "sell.cocaina",
	"process.cocaina",
	"police.handcuff",
	"favela.dom"
  },
     ["Sub Chefe Corleone"] = {
    _config = { gtype = "job" },
	"corleone.gunshops",
	"harvest.weed",
	"harvest.cocaina",
    "sell.cocaina",
	"process.cocaina",
	"police.handcuff",
	"favela.dom"
	
  }, 
	 
	 ["[VENDEDOR] Corleone"] = {
	"corleone.gunshops"

  },
     ["Máfia Corleone"] = {
    _config = { gtype = "job" },
	"corleone.gunshops",
	"harvest.weed",
	"harvest.cocaina",
    "sell.cocaina",
	"process.cocaina",
	"police.handcuff",
	"favela.dom"
  },
  
   ["Sub Chefe Comando Vermelho"] = {
    _config = { gtype = "job" },
	"harvest.metanfetamina",
	"process.metanfetamina",
	"mission.delivery.metanfetamina",
	"sell.metanfetamina",
	"mission.delivery.pot3",
	"police.seize.weapons",
	"police.handcuff",
	"favela.dom"
  }, 

   ["B.D Comando Vermelho"] = {
    _config = { gtype = "job" },
	"harvest.metanfetamina",
	"process.metanfetamina",
	"mission.delivery.metanfetamina",
	"sell.metanfetamina",
	"mission.delivery.pot3",
	"police.seize.weapons",
	"police.handcuff",
	"favela.dom"
  },

   ["Membro Comando Vermelho"] = {
    _config = { gtype = "job" },
	"harvest.metanfetamina",
	"process.metanfetamina",
	"sell.metanfetamina",
	"mission.delivery.metanfetamina",
	"mission.delivery.pot3",
	"police.seize.weapons",
	"police.handcuff",
	"favela.dom"
  },    
  
  ["A.L"] = {
    _config = { gtype = "job" },
	"favela.dom",
    "harvest.weed",
	"process.weed",
	"sell.weed"
  },
  
  ["Lider M.L"] = {
    _config = { gtype = "job" },
	"player.group.add",
    "player.group.remove",
	"process.Tartaruga",
    "harvest.tartaruga",
	"favela.dom"
  },
    ["Traficante de Armas"] = {
	"build.gun",
	"mission.delivery.pistol",
	"mission.delivery.shotgun",
	"mission.delivery.smg",
	"mission.gunrunner.shipment"
  },
  
  ["M.L"] = {
    _config = { gtype = "job" },
	"process.Tartaruga",
    "harvest.tartaruga",
	"favela.dom"
  },
  
  ["Assassino Profissional"] = {
    _config = { gtype = "job" },
	"hitman.takebounty",
    "-hitman.addbounty",
	"-player.blips",
	"mission.hitman"
  },
  ["Hacker"] = {
    _config = { gtype = "job" },
	"-player.blips",
	"sell.clonedcards",
	"pick.toclonecards",
	"clone.cards",
	"hacker.hack"
  },
  ["mugger"] = {
    _config = { gtype = "job" },
	"-player.blips",
	"mugger.mug"
  },
  ["Advogado"] = {
    _config = { gtype = "job" },
	"advogado.oab",
	"advogado.service"
  },  
  ["Transportador de Valores"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Você é um piloto de carro forte."}) end
	},
	"mission.bankdriver.moneybank",
	"mission.bankdriver.moneybank2",
	"bankdriver.vehicle",
	"bankdriver.paycheck",
	"bankdriver.money"
  },  
  ["Desempregado"] = {
    _config = { gtype = "job" },
	"player.paycheck"
  },
  
  -- garimpos
   ["Minerador de Ouro"] = {
    _config = { gtype = "job" },
	"harvest.ouro",
	"process.ouro",
	"venda.ouro"
  },
  ["Minerador de Diamante"] = {
    _config = { gtype = "job"},
    "pegar.diamante",
    "process.diamante",
	"bolsafamilia.paycheck",
    "sell.diamante"
  }, 
    ["Lenhador"] = {
    _config = { gtype = "job"},
    "pegar.madeira",
    "process.madeira",
	"bolsafamilia.paycheck",
    "Venda.Madeira"
  }, 
  ["Minerador de Ferro"] = {
    _config = { gtype = "job"},
    "pegar.ferro",
    "process.ferro",
	"bolsafamilia.paycheck",
    "sell.ferro"
  },  
   ["[VENDEDOR] Moto Clube"] = {
    "mc.gunshops"
  },

    ["Sedex"] = {
    _config = { gtype = "job" },
	"sedex.permissao",
	"sedex.garagem",
	"sedex.paycheck"
  },
    ["Lenhador"] = {
    _config = { gtype = "job" },
    "harvest.madeira",
	"process.madeira",
	"sell.madeira"
  },
  
    ["Lixeiro"] = {
    _config = { gtype = "job" },
    "lixeiro.permissao",
	"sedex.garagem",
	"sedex.paycheck"
  },
   ["Traficante de LSD"] = {
    _config = { gtype = "job" },
    "coletar.LSD",
	"vender.LSD"
  },
  -- pescador
  
  ["Pescador"] = {
    _config = { gtype = "job" },
	"vender.peixes",
	"pescar.peixes",
    "fisher.service",
	"fisher.vehicle",
	"pescador.paycheck",
	"traje.pescador"
  }
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "superadmindono",
    "admindono"
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["Agencia de Empregos"] = {
    _config = {x = -268.363739013672, y = -957.255126953125, z = 31.22313880920410, blipid = 351, blipcolor = 47},
	"Taxi",
	"Transportador de Valores",
    "Mecânico",
	"Entregador",
	"Pescador",
	"Sedex",
	"Lenhador",
	"Lixeiro",
	"Advogado",
	"Chaveiro",
	"Jornalista",
	"Prostituta",
	"Desempregado",
        "Minerador de Ouro"
  },
  ["Empregos Ilegais"] = {
    _config = {x = 707.324462890625, y = -966.986511230469, z = 30.4128551483154, blipid = 351, blipcolor = 49},
	"Ladrão de Carros",
	"Traficante de Metanfetamina",
	"Traficante de Orgãos",
	"Traficante de LSD",
	"Traficante de Maconha",
	"Traficante de Tartaruga",
	"Traficante de Cocaina",	
	"Hacker"
  } 
}

return cfg

